baseURL = "https://intermezzio.me"
languageCode = "en-us"
title = "Andrew Mascillaro"
theme = "hugo-profile"
publishDir = "docs"
Paginate = 3
# disqusShortname = "gurusabarish"
# googleAnalytics = "G-DWJJVE27WD"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Menus]

  # [[Menus.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   title = "Blog posts"
  #   url = "/blogs"
  #   weight = 1

  # [[Menus.main]]
  #   identifier = "dropdown"
  #   title = "Example dropdown menu"
  #   name = "Dropdown"
  #   weight = 2

  # [[Menus.main]]
  #   identifier = "dropdown1"
  #   title = "example dropdown 1"
  #   name = "example 1"
  #   url = "/#"
  #   parent = "dropdown"
  #   weight = 1

  # [[Menus.main]]
  #   identifier = "dropdown2"
  #   title = "example dropdown 2"
  #   name = "example 2"
  #   url = "/#"
  #   parent = "dropdown"
  #   weight = 2

[params]
  title = "Andrew Mascillaro"
  description = "My portfolio and development experience"
  # staticPath: ""  # The path to serve the static files from
  favicon = "/favicon.png"

  [params.theme]
    disableThemeToggle = false
  # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  [params.hero]
    enable = true
    intro = "Hi, my name is"
    title = "Andrew."
    subtitle = "I write practical software"
    content = "A passionate full-stack developer. I explore new technologies by creating useful software tools for myself and the greater community that are written with users and maintainers in mind."
    image = "/images/logo.png"

    # [params.hero.button]
    #   enable = true
    #   name = "Resume"
    #   url = "#"

    [params.hero.socialLinks]

      [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/"

      [[params.hero.socialLinks.customIcons]]
        icon = "/stackoverflow.svg"
        url = "https://stackoverflow.com/users/12940893/andrew-mascillaro"

      [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/andrew-mascillaro/"

      [[params.hero.socialLinks.customIcons]]
        icon = "/devpost-seeklogo.com.svg"
        url = "https://devpost.com/intermezzio"

  # About
  [params.about]
    enable = true
    title = "About Me"
    image = "/images/me.jpg"
    content = "I am a software engineer with a passion for automation. I study electrical and computer engineering, and I try to make software projects that people around me and in the greater community can use to improve their lives. I've interned at a few companies and build and maintain open source projects."

    [params.about.skills]
      enable = true
      title = "These are some of the technologies I've been working with recently:"
      items = ["Python", "Java", "JavaScript", "Heroku", "HTML/CSS", "Bash", "GCP", "HTML/CSS"]

  # Experience
  [params.experience]
    enable = true

    [[params.experience.items]]
      job = "Software Engineering Intern"
      company = "Tableau"
      companyUrl = "https://www.tableau.com/"
      date = "May 2021 - Present"
      content = """I am currently a software engineering intern at Tableau in Seattle, WA, where \
        I drove a feature that collects telemetry (diagnostics) data for Tableau users.\n\n\
        - Ran design and security meetings\n\
        - Wrote Java code that interfaced a Google BigQuery and a Tableau Dashboard\n\
        - Passed the Tableau Desktop Specialist certification\n\
        - Became a finalist in an internal, Salesforce-wide pitch competition
        """

      [params.experience.items.info]
        enable = true
        content = "I'm working as a software engineering intern for two consecutive summers."

      [params.experience.items.featuredLink]
        enable = true
        name = "View the certification"
        url = "https://www.credly.com/badges/7f00692c-e046-4bf5-be85-9fab32f8acbd"

    [[params.experience.items]]
      job = "Technical Spec (Systems) Engineering Intern"
      company = "Lockheed Martin"
      companyUrl = "https://example.com"
      date = "Jan 2021 - May 2021"
      content = """I worked as a systems engineering intern at Lockheed Martin. Much of my work involved the following:\n\n\
      - Built automation tests for Linux and Windows\n\
      - Drove a feature that would convert ships' status monitors into data-driven platforms
      """

      # [params.experience.items.featuredLink]
      #   enable = true
      #   url = "https://example.com"

      [params.experience.items.info]
        enable = true
        content = "I worked as a part-time systems engineering intern for one semester while enrolled full-time in college."

    [[params.experience.items]]
      job = "Remote Sensing Teaching Assistant"
      company = "MIT Beaver Works"
      companyUrl = "https://beaverworks.ll.mit.edu/CMS/bw/BWSI"
      date = "July 2019 - Aug 2020"
      content = """I helped teach a course about how to use computer science for natural disaster response.\n\n\
      - Analyzed aerial imagery in Python using computer vision and machine learning\n\
      - Taught how to use the Linux command line, including Git, SSH, and more\n\
      - Built three websites for documenting the course and its projects
      """

      [params.experience.items.info]
        enable = true
        content = "I worked as a teaching assistant for two consecutive summers at the first two iterations of this course."

      [params.experience.items.featuredLink]
        enable = true
        name = "View the course website I built"
        url = "https://bwsi-hadr.github.io/00-course-overview/"

    [[params.experience.items]]
      job = "Software Engineering Intern"
      company = "iCims"
      companyUrl = "https://www.icims.com/"
      date = "Sep 2018 - Jan 2019"
      content = "I worked on localization practices for iCims by changing key names in language resource bundles using Python and Java."

      [params.experience.items.info]
        enable = true
        content = "I was a part-time software engineering intern as part of a mentorship program my senior year of high school."

    [[params.experience.items]]
      job = "Teaching Assistant"
      company = "Olin College"
      companyUrl = "https://www.olin.edu"
      date = "Jan 2021 - Present"
      content = """I have been a teaching assistant for many technical classes in college and a personal tutor since high school. \
      I also led an initiative to teach first-years Python during the remote year when it was removed from an introductory course.\n\n\
      - Software Design\n\
      - Engineering Systems Analysis, including Signal Processing\n\
      - Introduction to Microelectronic Circuits\n\
      - Data Science\n\
      - Calculus, Python, Java, C++, Spanish, English (high school)
      """

  [params.education]
    enable = true

    # [[params.education.items]]
    #   title = "Master of Business Administration"
    #   date = "2013 - 2015"
    #   GPA = "3.8 out of 5.0"
    #   content = "Extracurricular Activities\n  - Lorem ipsum dolor sit amet consectetur adipisicing elit. \n  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."

    #   [params.education.items.school]
    #     name = "University of California, Berkeley"
    #     url = "https://example.org"

    [[params.education.items]]
      title = "Bachelor of Science in Electrical and Computer Engineering"
      date = "2019 - 2023"
      GPA = "3.79 out of 4.0"
      content = """Recipient of a 50% tuition merit scholarship\n\n\
      Extracurricular Activities\n\
      - Chair of the Honor Board (Student Government branch for integrity and justice)\n\
      - Rocketry\n\
      - President of the Christian Fellowship Club\n\
      - Formula SAE\n\
      - GRAVL autonomous tractor\n\
      - Ultimate Frisbee team\n\
      - Andrew Quartet
      """

      [params.education.items.school]
        name = "Franklin W. Olin College of Engineering"
        url = "https://example.org"

      # [params.education.items.featuredLink]
      #   enable = true
      #   name = "My academic record"
      #   url = "https://example.com"

    [[params.education.items]]
      title = "High School"
      GPA = "96.17 out of 100.0"

      [params.education.items.school]
        name = "High Technology High School"
        url = "https://www.hths.mcvsd.org/"

      # [params.education.items.featuredLink]
      #   enable = true
      #   url = "https://example.com"

  [params.achievements]
    enable = true

    [[params.achievements.items]]
      title = "Featured on GitHub's Release Radar"
      content = "Built Weffe, an open source Linux package for webcam effects on video calls"
      url= "https://github.blog/2022-01-21-release-radar-dec-2021/"

    [[params.achievements.items]]
      title = "Top 10 Finalist Hack at PennApps 2019"
      content = "Built an ML lip reader in 36 hours with my team"
      url = "https://devpost.com/software/speakinto-space"

    [[params.achievements.items]]
      title = "Best Google Cloud Project at Pennapps 2020"
      content = "Built AutoTOS, an accurate ML Terms of Service summarizer."
      url = "https://devpost.com/software/auto-tos"

    [[params.achievements.items]]
      title = "Best Data Visualization Hack, University of Iowa 2021"
      content = "Trained a hate speech detection model that accurately classified chess as not hate speech."
      url = "https://devpost.com/software/placeholder-name-vt6w4a"

    # [[params.achievements.items]]
    #   title = "Google Summer of Code"
    #   content = "Contributed to a open source project."
    #   url = "https://example.com"

  [params.projects]
    enable = true

    [[params.projects.items]]
      title = "AutoTOS"
      content = "Accurately summarize Terms of Service agreements with an ML model trained on ToS;DR data."
      image = "/images/projects/autotos.png"

      [params.projects.items.featured]
        name = "Demo"
        link = "http://autotos.me/"

    [[params.projects.items]]
      title = "Weffe"
      content = "A CLI for webcam filters, like blurred background, on Linux written in Bash. Published as an AUR (Arch Linux) package and installable on all Linux distributions."
      image = "/images/projects/weffe.png"

      [params.projects.items.featured]
        name = "See Documentation"
        link = "https://github.com/intermezzio/weffe"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/weffe"

    [[params.projects.items]]
      title = "Dining Hall Scraper"
      content = "Scrape Olin College's dining hall website and send emails about upcoming meals. Fully hosted on GitHub + Heroku with over 10% of the student body subscribed to the emails."
      image = "/images/projects/dining-hall-scraper.jpg"

      [params.projects.items.featured]
        name = "Deploy"
        link = "https://heroku.com/deploy?template=https://github.com/intermezzio/olin-dining-scraper"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/olin-dining-scraper"

    [[params.projects.items]]
      title = "Carbon Fiber Gantry Winder"
      content = "Control servo motors with an Arduino and manage circuit design and power output to precisely wind carbon fiber on tubes."
      image = "/images/projects/sidewinder.png"

      [params.projects.items.featured]
        name = "Presentation"
        link = "https://docs.google.com/presentation/d/1T52RFzbxPQFs9rQi_3F7M3jam2BZuMQauECE35gU2Jk"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/carbon-fiber-gantry-winder"

      [[params.projects.items.links]]
        icon = "fa fa-book"
        url = "https://docs.google.com/document/d/1PVhI5v9zD6sIoxYN8U0IB63Yk8t0yiwN4OAXvIWS76M"

    [[params.projects.items]]
      title = "Stack Exchange Contributor"
      content = "I answer a variety of questions on StackOverflow and the Unix Stack Exchange sites, including a lot of questions on Python and Pandas."
      image = "https://stackexchange.com/users/flair/17817750.png"

      [params.projects.items.featured]
        name = "See Profile"
        link = "https://stackexchange.com/users/17817750/intermezzio"

    [[params.projects.items]]
      title = "BB-8 Robot"
      content = "Worked with a team to build a spherical BB-8 robot, focusing on Arduino code, bluetooth modules, circuit design, and the project site."
      image = "/images/projects/bb-gr8.png"

      [params.projects.items.featured]
        name = "Project Site"
        link = "https://olincollege.github.io/pie-2021-03/BB-GR8/"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/bb-8"

    [[params.projects.items]]
      title = "Automated Stock Trading"
      content = "Created a cloud-hosted bot that accesses stock data, runs an algorithm, and paper trades stocks via the Alpaca Trading API."
      image = "/images/projects/automated-stock-trading.png"

      [params.projects.items.featured]
        name = "Automation Code"
        link = "https://github.com/intermezzio/automated-stock-trading"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/automated-stock-trading"

    [[params.projects.items]]
      title = "Chess Engine"
      content = "Designed an alpha-beta search algorithm with a friend that outperforms most chess players."
      image = "/images/projects/chess-engine.jpg"

      [params.projects.items.featured]
        name = "Source Code"
        link = "https://github.com/intermezzio/chess-engine"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/chess-engine"

    [[params.projects.items]]
      title = "Mentor Matching"
      content = "A full-stack application in Python/Flask, JQuery, and HTML/CSS/JS that connects technical mentors to mentees. Submitted to HackPrinceton 2019."
      image = "/images/projects/mentor-matching.png"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/mentor-matching"

      [params.projects.items.featured]
        name = "See Submission"
        link = "https://devpost.com/software/mentors-in-tech"

    [[params.projects.items]]
      title = "Sustainable Wealth Initiative"
      content = "Calculates estimated net worth over time and web scrapes for clean-energy stocks to invest in. Submitted to YHack (Yale) 2019."
      image = "/images/projects/sustainable-wealth.jpg"

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/intermezzio/mentor-matching"

      [params.projects.items.featured]
        name = "See Submission"
        link = "https://devpost.com/software/mentors-in-tech"
      # [[params.projects.items.links]]
      #   icon = "fab fa-github"
      #   url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
    enable = true
    content = "My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!"
    email = "nmfzo6x1@duck.com"
    btnName = "Mail me"

  [params.footer]
    recentPosts = false
    # [params.footer.socialNetworks]
    #   github = "https://github.com"
    #   linkedin = "https://linkedin.com"
    #   twitter = "https://twitter.com"
    #   instagram = "https://instagram.com"
    #   facebook = "https://facebook.com"
